language: cpp

os:
  - linux
  - osx

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

env:
  global:
    - SDK_INSTALL_PREFIX="$HOME/uroot/usr/local"
    - LD_LIBRARY_PATH="$SDK_INSTALL_PREFIX/lib:$SDK_INSTALL_PREFIX/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH"
    - DYLD_LIBRARY_PATH="$SDK_INSTALL_PREFIX/lib"
    - DYLD_FRAMEWORK_PATH="/usr/local/opt/qt5/lib"

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      sudo apt-add-repository -y ppa:beineri/opt-qt562-trusty                                   &&
      sudo apt-get update -qq                                                                   &&
      sudo apt-get install -qq libgl1-mesa-dev libglu1-mesa-dev                                 &&
      sudo apt-get install -qq qt56base qt56declarative qt56tools qt56webengine qt56xmlpatterns &&
      sudo apt-get install -qq libwrap0 libwrap0-dev                                            ;
    else
      brew update > /dev/null                                                                        &&
      cd $(brew --prefix)/Homebrew/Library/Taps/homebrew/homebrew-core/Formula                       &&
      echo "Install Qt 5.6."                                                                         &&
      wget -O qt5.rb https://raw.githubusercontent.com/Homebrew/homebrew-core/fdfc724/Formula/qt5.rb &&
      cd -                                                                                           &&
      brew install qt5                                                                               &&
      brew install openssl                                                                           &&
      chmod -R 755 /usr/local/opt/qt5/*                                                              ;
    fi

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      . /opt/qt56/bin/qt56-env.sh                                                                                  &&
      wget --directory-prefix=$HOME http://trueta.udg.edu/apt/ubuntu/devel/0.14/starviewer-sdk-linux-0.14-4.tar.xz &&
      mkdir ~/uroot                                                                                                &&
      tar xf ~/starviewer-sdk-linux-0.14-4.tar.xz -C ~/uroot                                                       ;
    else
      QTDIR="/usr/local/opt/qt5"                                                                                        &&
      PATH="$QTDIR/bin:$PATH"                                                                                           &&
      LDFLAGS=-L$QTDIR/lib                                                                                              &&
      CPPFLAGS=-I$QTDIR/include                                                                                         &&
      wget -nv --directory-prefix=$HOME http://trueta.udg.edu/apt/macosx/devel/0.14/starviewer-sdk-macosx-0.14-4.tar.xz &&
      mkdir ~/uroot                                                                                                     &&
      tar xf ~/starviewer-sdk-macosx-0.14-4.tar.xz -C ~/uroot                                                           ;
    fi

before_script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export DISPLAY=:99.0         &&
      sh -e /etc/init.d/xvfb start ;
    fi

script:
  - cd starviewer
  - if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "${CC}" = "clang" ]; then
      qmake -spec linux-clang ;
    else
      qmake ;
    fi
  - make -j3 | sed 's/\/Applications\/Xcode\.app\/Contents\/Developer/[xcode]/g' | sed -E 's/\/(Users|home)\/travis\/uroot/[uroot]/g'
  - cd tests/auto
  - ./autotests -silent
